<?php

/**********************************************************************
* R.One Creative Wordpress Theme
*
* File name:
*      functions.php
* Brief:
*      Wordpress functions
* Author:
*      R.One Creative
* Author URI:
*      http://r1creative.net
* Contact:
*      info@r1creative.net
***********************************************************************/

/* ==  WARNING! DO NOT EDIT THIS FILE! (PLEASE)  ==============================
*
*	  If you know what you're doing and would like to add your own custom
*     functions to this theme, DO NOT EDIT THIS FILE. Instead, use the
*     custom-functions.php file to defin e custom functions. Adding your
*     custom functions there will make it much easier to upgrade to a newer
*	  version of this theme without losing any of your customizations.
*
* ============================================================================*/

class _TSFTheme{
    public function __construct(){
        // Add some constants
		$this->constants();

        // Additional Init Functions
		$this->include_action_hook();

        // Thaumbnail Theme Support
        add_theme_support( 'post-thumbnails' );

        if( function_exists('acf_add_options_page') ) {
            // add parent
            $parent = acf_add_options_page(array(
                'page_title' 	=> 'Theme Options',
                'menu_title' 	=> 'Theme Options',
                'redirect' 		=> false
            ));
        }

        register_nav_menus( 
            array(
                'primary_nav' => 'Primary Menu',
                'quick_links' => 'Quick Links'
            ) 
        );

        add_editor_style( 'assets/css/app.css' );
    }
    /**
	 * Define some constants variables
	 */
	public function constants(){
		define( '_TSF_THEME_DIR', get_stylesheet_directory() );
		define( '_TSF_THEME_URI', get_stylesheet_directory_uri() );
	}

    /**
	 * Include action hooks
	 */
	public function include_action_hook(){
		// Enqueue style and javascripts
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_script_and_styles' ) );

        // Admin script
        add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_scripts_styles' ) );

        // Register Custom Post Type
        add_action( 'init', 'wpdocs_codex_team_init' );
        add_action( 'init', 'wpdocs_codex_service_init' );

        // Dashboard Customize
        remove_action( 'welcome_panel', 'wp_welcome_panel' );

        function wpex_wp_welcome_panel() { ?>
            <div id="custom-welcome-screen">
                <div class="custom-welcome-header">
                    <img src="<?php echo get_stylesheet_directory_uri() ?>/dashboard-welcome-contents/images/dash_logo.png" />
                    <h2 class="c-dashboard__title">Welcome to your dashboard!</h2>
                </div>
                <hr />
                <div class="custom-welcome-body">
                    <div class="task-button-panel">
                        <ul class="task-buttons">
                            <li class="task-button">
                                <a href="post.php?post=29&action=edit">Homepage</a>
                            </li>
                            <li class="task-button">
                                <a href="post.php?post=16&action=edit">Services Page</a>
                            </li>
                            <li class="task-button">
                                <a href="post.php?post=20&action=edit">Industries Page</a>
                            </li>
                            <li class="task-button">
                                <a href="post.php?post=10&action=edit">About Us Page</a>
                            </li>
                            <li class="task-button">
                                <a href="post.php?post=18&action=edit">Jobs Page</a>
                            </li>
                            <li class="task-button">
                                <a href="post.php?post=25&action=edit">Contact Page</a>
                            </li>
                            <li class="task-button">
                                <a href="edit.php?post_type=our-team">Team</a>
                            </li>
                            <li class="task-button">
                                <a href="admin.php?page=acf-options-theme-options">Header & Footer</a>
                            </li>
                            <li class="task-button">
                                <a href="admin.php?page=gf_entries">Form Entries</a>
                            </li>
                            <li class="task-button">
                                <a href="admin.php?page=acf-options-theme-options#field_64aea1dc671ae">Social Links</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="custom-welcome-footer">
                    <a href="http://r1creative.net" target="_blank">BUILT BY R. ONE CREATIVE</a>
                </div>
            </div>
        <?php }
        add_action( 'welcome_panel', 'wpex_wp_welcome_panel' );

        function remove_dashboard_widgets() {
            global $wp_meta_boxes;

            unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_quick_press']);
            unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_secondary']);
            unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_incoming_links']);
            unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_right_now']);
            unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_plugins']);
            unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_recent_drafts']);
            unset($wp_meta_boxes['dashboard']['normal']['core']['dashboard_recent_comments']);
            unset($wp_meta_boxes['dashboard']['side']['core']['dashboard_primary']);
        }

        // add_action('wp_dashboard_setup', 'remove_dashboard_widgets' );

        function r1_custom_welcome_screen_styles(){
            $externalStyles = '<link rel="stylesheet" href="'.get_stylesheet_directory_uri().'/dashboard-welcome-contents/dashboard.css">';
            echo $externalStyles;
        }

        add_action( 'admin_print_styles-index.php', 'r1_custom_welcome_screen_styles' );

    }

    /**
	 * Enqueue style and javascripts
	 */
    public function enqueue_script_and_styles(){
        // Load the Stylesheet
        wp_enqueue_style( 'r1-font-awesome-style',  'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css', array(), '');
        wp_enqueue_style( 'r1-theme-style',         _TSF_THEME_URI.'/style.css', array(), time() );
        wp_enqueue_style( 'r1-bulma-style',         _TSF_THEME_URI.'/assets/css/bulma.min.css', array(), '' );
        wp_enqueue_style( 'r1-slick-style',         _TSF_THEME_URI.'/assets/css/slick.min.css', array(), '' );
        wp_enqueue_style( 'r1-animate-style',       _TSF_THEME_URI.'/assets/css/animate.css', array(), time(), false );
        wp_enqueue_style( 'r1-fonts-style',         _TSF_THEME_URI.'/assets/css/fonts.css', array(), '' );
        wp_enqueue_style( 'r1-main-style',          _TSF_THEME_URI.'/assets/css/app.css', array(), time(), false );

        // Load the Scripts
        wp_enqueue_script(' r1-slick-scripts',      _TSF_THEME_URI .'/assets/js/slick.min.js', ['jquery'], '', true );
        wp_enqueue_script( 'r1-wow-scripts',        _TSF_THEME_URI . '/assets/js/wow.js', array('jquery'), time(), true);
        wp_enqueue_script( 'r1-main-scripts',       _TSF_THEME_URI . '/assets/js/app.js', array('jquery'), time(), true);

        if(is_page_template('tpl-about.php')){
        // wp_enqueue_script( 'r1-video-scripts',      _TSF_THEME_URI . '/assets/js/video-play.js', array('jquery'), time(), true);
        }

        wp_localize_script( 'TSF-main-scripts', 'ad_vars', array(
            'ajax_url' => admin_url( 'admin-ajax.php' ),
            'theme_uri' => _TSF_THEME_URI,
            'theme_dir' => _TSF_THEME_DIR,
            'site_url' => get_bloginfo('url')
        ));
    }

    /**
     * Enqueue scripts and styles
     */
    public function enqueue_scripts_styles(){
        // Enqueue Scripts
        wp_enqueue_script( 'admin-custom-scripts', _TSF_THEME_URI . '/dashboard-welcome-contents/script.js', array('jquery'), time(), true );

        wp_localize_script(
            'admin-custom-scripts',
            'TSF_scripts_js_vars',
            array(
                'ajax_url' => admin_url( 'admin-ajax.php' ),
                'stylesheet_url' => _TSF_THEME_URI,
                'stylesheet_dir' => _TSF_THEME_DIR
            )
        );
    }
}

new _TSFTheme();


/**
 * Register a custom post type
**/
//? Team
function wpdocs_codex_team_init() {
	$labels = array(
		'name'                  => 'Our Teams',
		'singular_name'         => 'Our Team',
		'add_new'               => 'Add New',
		'add_new_item'          => 'Add New Team',
		'edit_item'             => 'Edit Our Team',
		'new_item'              => 'New Team',
		'all_items'             => 'All Teams',
		'view_item'             => 'View Our Team',
		'search_items'          => 'Search Our Teams',
		'not_found'             => 'No teams found.',
		'not_found_in_trash'    => 'No teams found in Trash.',
		'parent_item_colon'     => 'Parent Teams:',
        'menu_name'             => 'Our Team', 'Admin Menu text',
		'featured_image'        => 'Team Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3',
	);

	$args = array(
		'labels'             => $labels,
		'public'             => true,
		'publicly_queryable' => true,
		'show_ui'            => true,
		'show_in_menu'       => true,
		'query_var'          => true,
		'rewrite'            => array( 'slug' => 'our-team' ),
		'capability_type'    => 'post',
		'has_archive'        => false,
		'hierarchical'       => true,
		'menu_position'      => null,
        'show_in_rest' => true,
		'supports'           => array( 'title' ),
	);

	register_post_type( 'our-team', $args );
}

//? Service
function wpdocs_codex_service_init() {
	$labels = array(
		'name'                  => 'Services',
		'singular_name'         => 'Service',
		'add_new'               => 'Add New',
		'add_new_item'          => 'Add New Service',
		'edit_item'             => 'Edit Our Service',
		'new_item'              => 'New Service',
		'all_items'             => 'All Services',
		'view_item'             => 'View Service',
		'search_items'          => 'Search Services',
		'not_found'             => 'No service found.',
		'not_found_in_trash'    => 'No service found in Trash.',
		'parent_item_colon'     => 'Parent Service:',
        'menu_name'             => 'Services', 'Admin Menu text',
		'featured_image'        => 'Service Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3',
	);

	$args = array(
		'labels'             => $labels,
		'public'             => true,
		'publicly_queryable' => true,
		'show_ui'            => true,
		'show_in_menu'       => true,
		'query_var'          => true,
		'rewrite'            => array( 'slug' => 'service' ),
		'capability_type'    => 'post',
		'has_archive'        => false,
		'hierarchical'       => true,
		'menu_position'      => null,
        'show_in_rest' => true,
		'supports'           => array( 'title', 'excerpt', 'editor', 'thumbnail' ),
	);

	register_post_type( 'service', $args );
}

add_filter( 'gform_disable_form_theme_css', '__return_true' );
add_filter( 'gform_disable_css', '__return_true' );

if (!function_exists('write_log')) {
	function write_log($log) {
		if (true === WP_DEBUG) {
			if (is_array($log) || is_object($log)) {
				error_log(var_export($log, true));
			} else {
				error_log($log);
			}
		}
	}
}


function enqueue_custom_scripts() {
    wp_enqueue_script('custom-script', get_template_directory_uri() . '/assets/js/video-play.js', array('jquery'), rand(), true);

    $about_page_id = 10; 
    $video_id = get_field('youtube_video_id', $about_page_id); 

    wp_localize_script('custom-script', 'videoData', array(
        'videoID' => $video_id
    ));
}
add_action('wp_enqueue_scripts', 'enqueue_custom_scripts');



